// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXabkXQf9RDc64d020mAZ9bLmFP4VYnVc',
    appId: '1:846044810097:web:885363cd8fa4ccccdf04d0',
    messagingSenderId: '846044810097',
    projectId: 'flutter-auth-project-adcd6',
    authDomain: 'flutter-auth-project-adcd6.firebaseapp.com',
    storageBucket: 'flutter-auth-project-adcd6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz18BwEqfvJQWJdVl-z9UKQuZpkhLK5qo',
    appId: '1:846044810097:android:6ba1e0d6caa11d71df04d0',
    messagingSenderId: '846044810097',
    projectId: 'flutter-auth-project-adcd6',
    storageBucket: 'flutter-auth-project-adcd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HEvY_8nqLV5GlSOgxp22guW6BHy1MRs',
    appId: '1:846044810097:ios:5218f11e1932feb6df04d0',
    messagingSenderId: '846044810097',
    projectId: 'flutter-auth-project-adcd6',
    storageBucket: 'flutter-auth-project-adcd6.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HEvY_8nqLV5GlSOgxp22guW6BHy1MRs',
    appId: '1:846044810097:ios:5218f11e1932feb6df04d0',
    messagingSenderId: '846044810097',
    projectId: 'flutter-auth-project-adcd6',
    storageBucket: 'flutter-auth-project-adcd6.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXabkXQf9RDc64d020mAZ9bLmFP4VYnVc',
    appId: '1:846044810097:web:6e60276c6dd1a671df04d0',
    messagingSenderId: '846044810097',
    projectId: 'flutter-auth-project-adcd6',
    authDomain: 'flutter-auth-project-adcd6.firebaseapp.com',
    storageBucket: 'flutter-auth-project-adcd6.firebasestorage.app',
  );
}
