final products = [
  {
    'id': 0,
    'title': 'Men\'s Casual Shirt',
    'price': 19.99,
    'image_url':
        'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQcMeuGmAUNwnlj5Z8k6PM377N6JB2yfjxtz8VCp_iMMN6NmOjDxQOpV2EcX7Yy-3lVjhMV__eNP2tNGIvQFWwWPqZb6SgTsnJEksrS5xMJtsZR4fMTAk0fPo4&usqp=CAc',
    'brand': 'Allen Solly',
    'size': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': 0,
    'title': 'Men\'s Casual Shirt',
    'price': 19.99,
    'image_url':
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO99CVsza57mPa8_KVbh-2ImuE13Z4U-4wzA&s',
    'brand': 'Allen Solly',
    'size': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': 0,
    'title': 'Men\'s Casual Shirt',
    'price': 19.99,
    'image_url':
        'https://houseofaldeno.com/cdn/shop/files/ALDENO6THOCT00801.jpg?v=1730098768&width=493',
    'brand': 'Allen Solly',
    'size': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': 0,
    'title': 'Men\'s Casual Shirt',
    'price': 19.99,
    'image_url':
        'https://hespoke.live/cdn/shop/files/solid-formal-burgundy-shirt-shirt-he-spoke-590696.jpg?v=1724821192&width=600',
    'brand': 'Allen Solly',
    'size': ['S', 'M', 'L', 'XL'],
  },
  {
    'id': 0,
    'title': 'Men\'s Casual Shirt',
    'price': 19.99,
    'image_url':
        'https://assets.myntassets.com/dpr_1.5,q_60,w_400,c_limit,fl_progressive/assets/images/28219632/2024/3/12/2f53aaab-40e1-4c5b-8148-6ad150e5f4341710256687634CampusSutraMenClassicOpaqueCheckedCasualShirt2.jpg',
    'brand': 'Allen Solly',
    'size': ['S', 'M', 'L', 'XL'],
  },
];

final List<Map<String, dynamic>> requestData = [
  {
    "id": 1,
    "title": "Men's Casual Shirt",
    "price": 1999,
    "discounted_price": 1199,
    "image_url":
        "https://images.asos-media.com/products/new-look-fine-stripe-oversized-shirt-in-mid-blue/207444679-1-midblue?fit=constrain",
    "brand": "Allen Solly",
    "size": ["S", "M", "L", "XL"],
    "description":
        "Purple & white vertical striped opaque casual shirt, has a button-down collar, full button placket, long regular sleeves, and curved hem",
    "material": "100% cotton",
    "color": "Purple & white",
    "fit": "Slim Fit",
    "rating": 4.5,
    "reviews": 529
  },
  {
    "id": 2,
    "title": "Men's Formal Blue Shirt",
    "price": 1799,
    "discounted_price": 1399,
    "image_url":
        "https://images.asos-media.com/products/new-look-short-sleeve-linen-blend-shirt-in-stone/205800250-1-stone?fit=constrain",
    "brand": "Van Heusen",
    "size": ["S", "M", "L", "XL"],
    "description": "Classic blue formal shirt, button-down collar, slim fit",
    "material": "Cotton",
    "color": "Blue",
    "fit": "Slim Fit",
    "rating": 4.3,
    "reviews": 450
  },
  {
    "id": 3,
    "title": "Men's White Slim Fit Shirt",
    "price": 1499,
    "discounted_price": 1099,
    "image_url":
        "https://images.asos-media.com/products/topman-long-sleeve-regular-fit-revere-plisse-shirt-in-beige/206385275-1-beige?fit=constrain",
    "brand": "Peter England",
    "size": ["M", "L", "XL"],
    "description": "White slim fit shirt with a modern look",
    "material": "Cotton",
    "color": "White",
    "fit": "Slim Fit",
    "rating": 4.5,
    "reviews": 320
  },
  {
    "id": 4,
    "title": "Men's Green Casual Shirt",
    "price": 1599,
    "discounted_price": 1299,
    "image_url":
        "https://images.asos-media.com/products/another-influence-micro-cord-utility-overshirt-in-grey/206700286-1-grey?fit=constrain",
    "brand": "U.S. Polo Assn.",
    "size": ["S", "M", "L", "XL"],
    "description": "Casual green shirt for a laid-back look",
    "material": "Cotton",
    "color": "Green",
    "fit": "Regular Fit",
    "rating": 4.2,
    "reviews": 380
  },
  {
    "id": 5,
    "title": "Men's Red Plaid Shirt",
    "price": 1999,
    "discounted_price": 1499,
    "image_url":
        "https://images.asos-media.com/products/native-youth-knitted-jacquard-stripe-long-sleeve-shirt-in-grey/206933273-1-grey?fit=constrain",
    "brand": "Levi's",
    "size": ["S", "M", "L"],
    "description": "Plaid red shirt for a trendy look",
    "material": "Cotton",
    "color": "Red Plaid",
    "fit": "Regular Fit",
    "rating": 4.3,
    "reviews": 400
  },
  {
    "id": 6,
    "title": "Men's Black Shirt",
    "price": 1799,
    "discounted_price": 1399,
    "image_url":
        "https://images.asos-media.com/products/lee-check-flannel-shirt-in-green/207166630-1-darkgreen?fit=constrain",
    "brand": "Tommy Hilfiger",
    "size": ["S", "M", "L", "XL"],
    "description": "Solid black shirt with a formal appeal",
    "material": "Cotton",
    "color": "Black",
    "fit": "Slim Fit",
    "rating": 4.6,
    "reviews": 510
  },
  {
    "id": 7,
    "title": "Men's Casual Blue Shirt",
    "price": 1699,
    "discounted_price": 1399,
    "image_url":
        "https://images.asos-media.com/products/abercrombie-fitch-long-sleeve-shirt-in-dark-green/207327522-1-darkgreen?fit=constrain",
    "brand": "H&M",
    "size": ["S", "M", "L", "XL"],
    "description": "Relaxed blue shirt for everyday wear",
    "material": "Cotton",
    "color": "Blue",
    "fit": "Regular Fit",
    "rating": 4.5,
    "reviews": 350
  },
  {
    "id": 8,
    "title": "Men's Casual Yellow Shirt",
    "price": 1699,
    "discounted_price": 1299,
    "image_url":
        "https://images.asos-media.com/products/abercrombie-fitch-cropped-slub-flannel-check-overshirt-in-brown/207327530-1-brown?fit=constrain",
    "brand": "Wrangler",
    "size": ["S", "M", "L"],
    "description": "Casual yellow shirt for a summer day",
    "material": "Cotton",
    "color": "Yellow",
    "fit": "Regular Fit",
    "rating": 4.4,
    "reviews": 390
  },
  {
    "id": 9,
    "title": "Men's Slim Fit Black Shirt",
    "price": 1999,
    "discounted_price": 1599,
    "image_url": "https://images.asos-media.com/products/hollister-boxy-western-shirt-in-grey-check/207356024-1-greycheck?fit=constrain",
    "brand": "Van Heusen",
    "size": ["M", "L", "XL"],
    "description": "Slim fit black shirt for a sleek look",
    "material": "Cotton",
    "color": "Black",
    "fit": "Slim Fit",
    "rating": 4.7,
    "reviews": 450
  },
  {
    "id": 10,
    "title": "Men's White Formal Shirt",
    "price": 2299,
    "discounted_price": 1799,
    "image_url": "https://images.asos-media.com/products/jack-jones-jersey-overshirt-in-black/207370213-1-black?fit=constrain",
    "brand": "Marks & Spencer",
    "size": ["S", "M", "L"],
    "description": "Classic white shirt for formal occasions",
    "material": "Cotton",
    "color": "White",
    "fit": "Slim Fit",
    "rating": 4.8,
    "reviews": 520
  },
  {
    "id": 11,
    "title": "Men's Blue Casual Shirt",
    "price": 1599,
    "discounted_price": 1199,
    "image_url": "https://images.asos-media.com/products/polo-ralph-lauren-oxford-shirt-in-slim-fit-blue/202566052-1-blue?fit=constrain",
    "brand": "U.S. Polo Assn.",
    "size": ["S", "M", "L", "XL"],
    "description": "Comfortable blue casual shirt for everyday use",
    "material": "Cotton",
    "color": "Blue",
    "fit": "Regular Fit",
    "rating": 4.5,
    "reviews": 450
  },
  {
    "id": 12,
    "title": "Men's Pink Shirt",
    "price": 2299,
    "discounted_price": 1899,
    "image_url": "https://images.asos-media.com/products/new-look-long-sleeve-muscle-fit-shirt-in-black/205794943-1-black?fit=constrain",
    "brand": "Levi's",
    "size": ["M", "L", "XL"],
    "description": "Sleek pink shirt for casual outings",
    "material": "Cotton",
    "color": "Pink",
    "fit": "Slim Fit",
    "rating": 4.6,
    "reviews": 460
  },
  {
    "id": 13,
    "title": "Men's Casual Green Shirt",
    "price": 1799,
    "discounted_price": 1399,
    "image_url": "https://images.asos-media.com/products/topman-long-sleeve-regular-fit-revere-plisse-shirt-in-beige/206385275-1-beige?fit=constrain",
    "brand": "Wrangler",
    "size": ["M", "L", "XL"],
    "description": "Casual green shirt for a comfortable look",
    "material": "Cotton",
    "color": "Green",
    "fit": "Regular Fit",
    "rating": 4.3,
    "reviews": 380
  },
  {
    "id": 14,
    "title": "Men's Orange Shirt",
    "price": 1799,
    "discounted_price": 1399,
    "image_url": "https://images.asos-media.com/products/another-influence-cord-utility-overshirt-in-navy/206700034-1-deepnavy?fit=constrain",
    "brand": "H&M",
    "size": ["M", "L", "XL"],
    "description": "Bright orange shirt for a bold look",
    "material": "Cotton",
    "color": "Orange",
    "fit": "Regular Fit",
    "rating": 4.4,
    "reviews": 420
  },
  {
    "id": 15,
    "title": "Men's Grey Shirt",
    "price": 1499,
    "discounted_price": 1099,
    "image_url": "https://images.asos-media.com/products/native-youth-knitted-jacquard-stripe-long-sleeve-shirt-in-grey/206933273-1-grey?fit=constrain",
    "brand": "Peter England",
    "size": ["S", "M", "L"],
    "description": "Casual grey shirt for relaxed wear",
    "material": "Cotton",
    "color": "Grey",
    "fit": "Slim Fit",
    "rating": 4.3,
    "reviews": 370
  }
];
